steps:
  # Authenticate Docker with Docker Hub using Secret Manager (without interactive prompt)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo $(gcloud secrets versions access latest --secret=docker-hub-password) | docker login -u "ireneengg2011" --password-stdin

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'ireneengg2011/assgn2:latest', '.']

  # Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'ireneengg2011/assgn2:latest']

  # Use the correct gcloud image for updating Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'my-instance'
      - '--zone=us-central1-a'
      - '--container-image=ireneengg2011/assgn2:latest'

# Enable Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY

# Define output Docker image
images:
  - 'ireneengg2011/assgn2:latest'
