steps:
  # ✅ Authenticate with Docker Hub using `gcr.io/cloud-builders/docker`
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud auth configure-docker
        echo "$$DOCKER_HUB_PASSWORD" | docker login -u "ireneengg2011" --password-stdin
    secretEnv: ['DOCKER_HUB_PASSWORD']

  # ✅ Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'ireneengg2011/assgn2:latest', '.']

  # ✅ Push the image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'ireneengg2011/assgn2:latest']

  # ✅ Update Compute Engine with the new container image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'my-instance'
      - '--zone=us-central1-a'
      - '--container-image=ireneengg2011/assgn2:latest'

# ✅ Ensure Cloud Build logs are enabled
options:
  logging: CLOUD_LOGGING_ONLY

# ✅ Define the Docker image being built
images:
  - 'ireneengg2011/assgn2:latest'

# ✅ Define Secret Manager access (Fixes YAML syntax issue)
availableSecrets:
  secretManager:
    - versionName: projects/789777965607/secrets/docker-hub-password/versions/latest
      env: 'DOCKER_HUB_PASSWORD'
